name: 'ProdSensor Analysis'
description: 'Run production readiness analysis on your codebase'
author: 'ProdSensor'
branding:
  icon: 'shield'
  color: 'green'

inputs:
  api-key:
    description: 'ProdSensor API key'
    required: true
  repo-url:
    description: 'Repository URL to analyze (defaults to current repository)'
    required: false
  fail-on:
    description: 'When to fail the build: "not-ready" (default), "blockers", or "never"'
    required: false
    default: 'not-ready'
  comment-on-pr:
    description: 'Post analysis results as a PR comment'
    required: false
    default: 'true'
  timeout:
    description: 'Maximum time to wait for analysis in seconds'
    required: false
    default: '600'
  api-url:
    description: 'ProdSensor API URL (for self-hosted instances)'
    required: false

outputs:
  verdict:
    description: 'Analysis verdict: PRODUCTION_READY, NOT_PRODUCTION_READY, or CONDITIONALLY_READY'
  score:
    description: 'Overall production readiness score (0-100)'
  run-id:
    description: 'Analysis run ID'
  report-url:
    description: 'URL to the full analysis report'
  blocker-count:
    description: 'Number of blocker-severity findings'
  major-count:
    description: 'Number of major-severity findings'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PRODSENSOR_API_KEY: ${{ inputs.api-key }}
    PRODSENSOR_API_URL: ${{ inputs.api-url }}
    INPUT_REPO_URL: ${{ inputs.repo-url }}
    INPUT_FAIL_ON: ${{ inputs.fail-on }}
    INPUT_COMMENT_ON_PR: ${{ inputs.comment-on-pr }}
    INPUT_TIMEOUT: ${{ inputs.timeout }}
    GITHUB_TOKEN: ${{ github.token }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}
